[workspace]
members = ["launcher", "il2cpp", "dumpcs-gen", "dumper"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
windows = "0.58.0"

il2cpp = {path = "il2cpp"}
dumpcs-gen = {path = "dumpcs-gen"}